<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;


function employee_registration_form_alter(&$form, &$form_state, $form_id) {
  // Check when the right form is passed.
  if ($form_id == 'employee_registration_form') {
    
    // Add the check box.
    $form['certify'] = array(
      '#type' => 'checkbox',
      '#title' => t('I certify that this is my true name'),
    );

    $form['start_date']['#weight'] = 1;
    $form['end_date']['#weight'] = 2;
    $form['submit']['#weight'] = 4;
    $form['certify']['#weight'] = 3;


  }
}


/**
 * Implements hook_help().
 */
function employee_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
  	case 'help.page.employee_registration':
  		$output = '';
      	$output .= '<h3>' . t('About') . '</h3>';
      	$output .= '<p>' . t('This module aims to build the custom employee forms.') . '</p>';
    return $output;
  }
}



?>
